- CMakeLists.txt
> OSX build fix

- README.md
I think this is a better band-aid for the location of the OSX executable. Maybe someone more knowledgeable with CMake (or me if I get around to it) can figure out a permanent fix.
> Update readme with slightly better workaround for OSX executable.

- examples/c++/CMakeLists.txt
For me on Fedora 23 C++ examples did not compile due to missing headers. Also example binaries were put to wrong folder and did not start because .so library was not found due to wrong RPATH in ELF binary.
> Fix missing / in path concat, caused wrong include and output dirs

- CMakeLists.txt
- cmake_modules/FindNumPy.cmake
- src/lib_python/ViZDoomGamePython.cpp
- src/lib_python/ViZDoomPythonModule.cpp
Significant changes include:
- Guard calls to import_array() in an initialization function (see https://mail.scipy.org/pipermail/numpy-discussion/2010-December/054345.html)
- Modify CMakeLists.txt to find the right version of libpython and libboost-python{3.x}
- Fix FindNumPy.cmake to use Python3 compatible print syntax
> Support building libpython on Python3

- doc/Building.md
I spent a few hours scouring the docs and issues for the best way to get rolling on osx. Added a quickstart section to make OSX installs less painful with virtualenv goodness from anaconda. 
- Add quick-start for anaconda, python 3, and osx
- Add brew based osx dependencies
- Add proper library configuration arguments
> Add quick-start for OSX

- doc/Building.md
This should fix a link from the TOC at top and from the top-level README.md.
> windows section referred to ask "windows_build"

- doc/DoomGame.md
> typo: "setDoomSkill" -> "set_doom_skill" 

- doc/Building.md
List of dependencies was missing "unzip" which is not necessarily included in *nix installations.
> Added missing dependency for "unzip" (for linux)

- doc/Building.md
Because wget is not default command at MacOS [this script](https://github.com/mwydmuch/ViZDoom/blob/master/scripts/download_freedoom.sh#L16) can be failed.
> Update MacOS dependencies

- examples/python/labels.py
- src/vizdoom/src/r_draw.cpp
- src/vizdoom/src/r_segs.cpp
This is a small modification I've added for a past project that uses semantic segmentation in ViZDoom.
We implemented full semantic segmentation,
where every pixel had a label such as pickup/enemy/other/walls/floor/ceiling,
and this was the only change to the C++ backend necessary.
This is definitely a hack at best,
but it worked well enough and wanted some advice on how to properly implement this.
> add walls, floors/ceilings to label buffer

- doc/FAQ.md
Writeup of how to (possibly) fix obscure `Buffers size mismatch` error on some Windows machines.
Issue #404 has the same content.
> Update FAQ with help for `Buffers size mismatch`

- src/lib/ViZDoomController.cpp
- src/lib/ViZDoomGame.cpp
Two fixes:
- Add missing `DoomController::waitForDoomWork` after sending initial `MSG_CODE_TIC` when replaying LMP file. Else all subsequent TIC/UPDATE/TIC+UPDATES get ACK intended for prior request.
- When running synchronously get last tic from controller's record of last tic rather than shared memory. In the case where Doom runs ahead (e.g., `Mode.SPECTATOR`, non-async) this produces the expected living rewards. (Note: the fact that Doom is running ahead in this case may be undesired behavior and a bug given what `Mode.SPECTATOR` is intended to do).
See https://github.com/mwydmuch/ViZDoom/issues/412
> Vizdoom vizdoomcontroller sync fix

- .gitignore
- .travis.yml
- CMakeLists.txt
- doc/Building.md
- doc/Quickstart.md
- scripts/assemble_luarocks_package.sh
- scripts/assemble_pip_package.bat
- scripts/assemble_pip_package.sh
- scripts/download_freedoom.bat
- scripts/download_freedoom.sh
- setup.py
- src/vizdoom/CMakeLists.txt
- src/vizdoom/gdtoa/CMakeLists.txt
ViZDoom would not compile on a fresh installation of Ubuntu 16.04/18.04 due an error as in Issue #394 
This was because the gdtoa lib include files (that are autogenerated when the gdtoa library is built) are needed by the main ViZDoom source but not included in the main project. This is addressed by the changes in this pull request by modifiying [src/vizdoom/gdtoa/CMakeLists.txt](https://github.com/hadjilucasL/ViZDoom/blob/51a970299ed57d23896e7ce9699f946b401142aa/src/vizdoom/gdtoa/CMakeLists.txt#L44) to expose `arith.h`.
I have also added the configurations needed to move the `./bin` directory outside of its fixed location inside the source root. As is standard when compiling a project with CMake, the user creates a build directory and then generates and compiles the project in there, …
> Updated build & transitioning away from python2

- src/vizdoom/game-music-emu/CMakeLists.txt
Fixes build failing with GCC versions 10 and up.
> Change regex to work with GCC 10+ versions.

- src/vizdoom/CMakeLists.txt
- src/vizdoom/src/CMakeLists.txt
Currently, usage of `${CMAKE_SOURCE_DIR}` during `${CMAKE_MODULE_PATH}` setup prevents ViZDoom as a subproject from correctly configuring.
This is because `${CMAKE_SOURCE_DIR}` in sub project will point to the top level CMakeLists.txt (aka parent project)'s directory:
```
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}" "${CMAKE_SOURCE_DIR}/cmake_modules")
```
will be substituted with
```
"${CMAKE_SOURCE_DIR};<parent project>;<parent project>/cmake_modules"
```
What's more, in `src/vizdoom/CMakeLists.txt`:
https://github.com/mwydmuch/ViZDoom/blob/ee8c6b10a09397981e38f1ba6c1bb9ef7eb204ab/src/vizdoom/CMakeLists.txt#L99
`CMAKE_MODULE_PATH` will be unconditionally set to `CMAKE_SOURCE_DIR`, thus preventing parent project from injecting correct module path at all. The final …
> Replace `CMAKE_SOURCE_DIR` with `PROJECT_SOURCE_DIR` when setting `CMAKE_MODULE_PATH`

- gym_wrapper/base_gym_env.py
- setup.py
- tests/test_gym_wrapper.py
Per https://github.com/openai/gym/issues/2892#issuecomment-1155823477 the new gym env checker will enforce calling `super().reset(seed=seed)` in the reset function. 
Also `warn` option ignore/deprecated for check_env so removed that. 
`gym.env.registry.all()` on line 13 in `test_gym_wrapper.py` is deprecated in this version (now want `values()` instead) but just raises a warning so I left it there because using `value()` breaks gym version 0.23
> Update gym version to  0.24

- examples/python/gym_wrapper.py
- gym_wrapper/base_gym_env.py
- gym_wrapper/gym_env_defns.py
- setup.py
- tests/test_gym_wrapper.py
Update `gym_wrapper`  to be compatible with the newly released version 0.26. 
Release note - https://github.com/openai/gym/pull/3056
Changes made here include;
1. Use of the new step API
2. Update the render; setting the render_mode on instantiation
3. Always return `info` on reset
4. Update the tests to conform to the new API
@pseudo-rnd-thoughts
> Update gym version to 0.26

- examples/python/learning_stable_baselines.py
Hey there :wave:  ,
There is an error in the stable baselines 3 vizdoom example.
We defined FRAME_SKIP=4 but we never use it. So it takes the default value (1).
Have a nice day :hugs:
> Update learning_stable_baselines.py (frame_skip error)

- .github/workflows/build-and-test.yml
- .github/workflows/build-docs.yml
- .github/workflows/build-wheels.yml
- CMakeLists.txt
- scripts/build_and_test.sh
- scripts/build_and_test_conda.sh
- scripts/install_and_test_wheel.sh
- setup.py
- src/lib_python/CMakeLists.txt
- src/lib_python/__init__.py.in
- tests/build_test_cibuildwheel_linux.sh
- tests/build_test_local_linux_builds.sh
This PR fixes the bug that caused not to include pybind11 in the source distribution and fixes manual building on some platforms.
> Building and CI/CD fixes

- .pre-commit-config.yaml
- pyproject.toml
This is a hotfix that aims to fix pre-commit checks that fail when using a new pyright 1.1.350 version.
> Revert pyright to the previous version

- examples/python/gymnasium_vect_bench.py
Gymnasium offers SyncVect and AsyncVect (plus custom as well) environments. We would like to benchmark the VizDoom within such environments.
This is motivated by this paper, [ https://arxiv.org/abs/2407.17032]( https://arxiv.org/abs/2407.17032). In this paper the authors compare simple and complex environments. Looking at the plot below from the paper for a complex environment (Lunar Lander):
So here I kinda reproduce the left plot on my desktop computer with the following specs:
Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
32G RAM
And here is the plot I was able to produce:
[UPDATED] included the data point at only 1 environment @mwydmuch.
It would be also interesting to test it also for better/slower machines as well.
So my conclusion is that Async in VizDoom is able to be faster than sync …
> [Benchmark] Benchmarking the VizDoom env in vectorized gymnasium

- .github/workflows/build-and-test-windows-wheels.yml
Fixes https://github.com/Farama-Foundation/ViZDoom/pull/628
@mwydmuch I've tested on my fork that this indeed fixes issue associated with 7z 25.01 security update.
https://github.com/Trenza1ore/ViZDoom-Contrib/actions/runs/16854707236
Feel free to rename this step before merging it if name is undesirable. 😉
> [Github Actions] Fix 7z version to 25.00 for installing boost

- CMakeLists.txt
Fixes the new error in manylinux wheel-building after https://github.com/Farama-Foundation/ViZDoom/pull/628
Boost < 1.70 may not ship with the config file required by `POLICY CMP0167`, and `1.66.0-13.el8` was used for building the manylinux wheel.
@mwydmuch
> [Github Actions] Disable CMake `POLICY CMP0167 NEW` behaviour when Boost version < 1.70
